// Auto-generated method definitions
// This will be populated by the build system

// Re-export methods generated by risc0-build
risc0_zkvm::guest::entry!(TRIAL_VERIFY_ELF, TRIAL_VERIFY_ID);

// Method IDs will be generated at build time
pub const TRIAL_VERIFY_ELF: &[u8] = &[];
pub const TRIAL_VERIFY_ID: [u32; 8] = [0; 8];
